export const REGISTER_FIELD = 'REGISTER_FIELD';
export const SELECT_ITEM = 'SELECT_ITEM';
export const RADIO_CHOOSE = 'RADIO_CHOOSE';
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';